use std::io::Write;
use std::path::PathBuf;
use std::process::Command;
use std::{env, fs};

extern crate form;
extern crate svd2rust;

fn main() {
    // Put the memory definitions somewhere the linker can find it
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    println!("cargo:rustc-link-search={}", out_dir.display());
    fs::copy("memory.x", out_dir.join("memory.x")).unwrap();
    println!("cargo:rerun-if-changed=memory.x");
    println!("cargo:rerun-if-changed=device.x");
    println!("cargo:rerun-if-changed=src/lib.rs");

    // If the svd file changes, rebuild this crate
    println!("cargo:rerun-if-changed=5a-75e_6.0.svd");
    let svd = String::from_utf8(include_bytes!("5a-75e_6.0.svd").to_vec())
        .expect("svd file wasn't valid utf8");

    // Generate config for riscv target
    let mut config = svd2rust::Config::default();
    config.target = svd2rust::Target::RISCV;

    // Generate the svd file to a string in RAM
    let pac_file = svd2rust::generate(&svd, &config).expect("couldn't generate file with svd2rust");

    // This appears to be what they do inside svd2rust:main.rs
    let lib_rs = pac_file.lib_rs.replace("] ", "]\n");

    // These strings are generated by svd2rust.  Remove them to silence warnings.
    let bad_strings = [
        "# ! [ deny ( legacy_directory_ownership ) ]",
        "# ! [ deny ( plugin_as_library ) ]",
        "# ! [ deny ( safe_extern_statics ) ]",
        "# ! [ deny ( unions_with_drop_fields ) ]",
        "#![no_main]",
        "# ! [ no_std ]",
    ];

    let mut out_file = fs::File::create("src/lib.rs").expect("couldn't open output file");
    for line in lib_rs.lines() {
        if bad_strings.contains(&line) {
            println!("Found bad string, skipping");
            continue;
        }
        out_file
            .write(line.as_bytes())
            .expect("couldn't write line to lib.rs");
        out_file
            .write(b"\n")
            .expect("couldn't write line ending to lib.rs");
    }
    Command::new("rustfmt")
        .arg("src/lib.rs")
        .spawn()
        .expect("Could not rustfmt sources");
}
